### ISSUE TITLE
Deprecation warning due to invalid escape sequences in Python 3.7

### ISSUE THREAD

**Issue by tirkarthi** [crdoconnor/dumbyaml#2]
Deprecation warning are generated over invalid escape sequences. This can be fixed by using raw strings or escaping the literals again.

```
find . -iname '*.py'  | xargs -P 4 -I{} python -Walways -m py_compile {}

./dumbyaml/yamlnode.py:7: DeprecationWarning: invalid escape sequence \-
  INT_REGEXP = re.compile("^(\-|\+)?[0-9]+$")
```

**Comment by crdoconnor** [comment]
This is an old, deprecated project. Please use strictyaml instead.

**Comment by tirkarthi** [comment]
Thanks for the update, closing.
